@startuml
'https://plantuml.com/component-diagram

!theme mono

!include <tupadr3/devicons2/nodejs>

'!include https://raw.githubusercontent.com/bondden/puml-sprites/main/uml/sprites.puml

!include ./sprites.puml

skinparam {
  linetype ortho
}

title Sprites Demo

component dns [
  <$dnsmasq*.4> dns
  --
  [[https://dnsmasq.org/doc.html dnsmasq]]
]

component tfk [
  <$traefik*.3> tfk
  --
  [[https://github.com/traefik/traefik/t traefik]]
]

rectangle ctl {

  component nxs [
    <$nexus*.3> nxs
    --
    [[https://github.com/sonatype/nexus-public Nexus]]
  ]
  
  component ptn [
    <$portainer*.3> ptn
    --
    [[https://github.com/portainer/portainer Portainer]]
  ]
  
  component elk [
    <$elk*.3> elk
    --
    [[https://github.com/elastic Elastic Stack]]
  ]

  component vmx [
    <$victoriametrics*.3>
    --
    [[https://github.com/VictoriaMetrics/VictoriaMetrics VictoriaMetrics]]
  ]

}

rectangle app {

  component api [
    <$nodejs*.5> api
    --
    Some API
  ]

  component lcn [
    <$langchain*.3> <$nvidia*.3> lcn
    --
    [[https://github.com/langchain-ai/langchain Langchain]]
    [[https://github.com/NVIDIA nVidia]] GPU
  ]
  
  component vdb [
    <$qdrant*.3> vdb
    --
    [[https://github.com/qdrant/qdrant Qdrant]]
  ]
  
  database dbc [
    <$clickhouse*.3> cdb
    --
    [[https://github.com/ClickHouse/ClickHouse ClickHouse]]
  ]
  
  collections agt [
    agt
    --
    Observability
    Agents
  ]
  
  api -- lcn
  lcn - vdb
  api - dbc

}

elk -- agt

tfk -- nxs
tfk -- api
tfk -- elk
tfk -- ptn
tfk -- vmx

vmx -- agt

app -r[#hidden]- dns

@enduml
