@startuml

' https://github.com/traefik/traefik
sprite $traefik [100x100/16z] {
xTT7beD040HHRX3tF-tOpHYfNuYGL-Kwcu-dsAwVoMGouJiN5gpI2NXSWzzvL8EB6t1f0ovjy6245xYei06FTRjwmlXT44eKjD85813XwU-2KFffyaeNF6BA
g4Z22ul5GZ34OWD2C8JOHYHE6Yk4u7PaqH2477waGJ2m1ieGbNhHTrmmZ19kVw_eVUmtfzk_eDXblXu4luBGzwk241HTxBj78_v7bP80e4f904J9AAoZIWXX
6TVoWcStsaGW1A4iAskbVABSXIgVslq_wQIv1Auu-_WEuT_9Zta14KAPAxpGlWPXTL7yIeIY1QzamIkTy8eNEk85hsWXAOh8YX0wOeIkIA4h228gUC5723r6
w354Zn5wXD1ZX1v3z0GXPJAPJDu1
}

' https://github.com/portainer/portainer
sprite $portainer [100x100/16z] {
xTa5KaLH40FHsK7slrgSHeAJ8BUcovxE-QxpXIHDe3LYXFf4MH5L1IeA8sbA2cCb0NQ4EmEb862mjV9mPH4bAc1adoqCCSEKZ83XnmHk9ZTS2GaO4SLFS-CB
TujI7MwGfxdEdkSi1EeOQwnnryyRQp2HXOB1GB7qSMCD-dbZ3Nz-58nz3gwnHk7v4IbcYBoGeTys536qneTROmsc10noWF86X5XKwWy44sYyXC4YoZDGysN4
2I_qUwxQ24GBWUeWf3AYZrK4A43K4FKDzGqTO0I8Wg5J3Arnm9r-m1CTf6vK2QeQL2UeIL2J89zgH1XX6yjnPOfz6xW4
}

' https://github.com/sonatype/nexus-public
sprite $nexus [100x100/16z] {
xTS7YWCm44DHdq3tl-qsqyF0vsUrTKH9i_pI1vz2DfjDKjdrvbvDsqZTIDh63JVMUAxFrh1LtZYdRfn_PgonnXfhh15Y9CyOWKQqaM0ZEIO9DBmIQ7WaZn5h
XE0LqPIAg1b4T4H32AZb2TppGeAwN1X-Wrm1nDG0Mr1XCC1BeS9a80K8Xyx1MPa8FmT3GaTTOXK_1x7oMNDG2C1WRnZjUmMN_JQLEQW4hrJde7WHvgLuWJVn
mZmkX-N-7EJ2O005F0hc8DZd--TWCXjG6GL_7cpFmHiX30Pe0e4RN04xYE5HdOF-KQ-KpeFYHHY52ruHtoQZz8_qIX1j8GW54GeHWb2481H128KAF48G4O98
cRWHWeWGH0GXuWIFd5w489NJZXBwUGK
}

' https://github.com/elastic
sprite $elk [100x100/16z] xSq50GH150MWr-3tJtlkBki31SX6zIW7_H_Lis6EwXG001aLK0y004161TJdSgLwqlFWSFJ0SSNXS3WSITz7CioHz7aamnnh

' https://github.com/qdrant/qdrant
sprite $qdrant [100x100/16z] {
xTQ7ShH030FWEzXYxVB-hvkclv0pO3onfqRJK_W6YVRmPAsjVwJLyaZAMZu4ffKrXQWK_Yfr2HTAxI-fzPbL4nCpYvxwG2bBs10a3fMw9fo4KigFfrP3H9_A
Ofn3mDrIb11TMAa6OLt7_gd3PrcAK_0_NaeZuKLQJQX9fPPRWbMJ_FWwheO035YpF1rFS1t1-0Z4KPXp20etb7QcFCsQnYvmpaBXHaq6OjoJvLPDJgLy4ufF
k3tBUljo0Wc_8dLdbD9S9x5NplznRDyD3c88hbF1t5wCJ-L88E5LA6ZZe302TW1TqtPYi32Z9akXS69GCGIhCDPqRkmB0mc_8XGk32eK_0XOas4mLmAkVDRq
GmDolPJ3C7OLP1a01Ief1WMbX1ciII6X1WL3SHksG2N8WF66335AFINc23AENvDylWOQfIf5i6sXngUYNdJXnhumFi6ZZRt28T8Cpe9jIpEeiAPKex0dvjVu
DNwDVchCkFSvsh4nHg01gTgO8zO0UjqP5C8DIDiP5C8DY5GQ72B9a5u_ZJaoZK_b770PWaE3GOnHcY3Ne89yezIER8E5vHfKa6im7Ta6Pyarg00HnhfUAYt2
U2o6qa-CkPd6VQNAaN7_VSuyJUNLc9l7O9R5cEM_mQCv3CSiD7WiX-4hhDFO6Bz1PRKA0m_aCknPGhuJzIpP1cT9DZXBji72iWqMbcrGIJPu7ISRVBMisGR7
FpScS64CPPYpQ6D85-34cEZt03tBs1_a-LXR1xJ1NpA-mlR6X2pyucW2l1eGzkH2gFmtHlz_aDPUtrnT2PvPQ4nfZtrg0_uPqzZQA8p67A9-rxhWovWGOmXR
6HDIzA--nlym1jGltm4
}

' https://github.com/langchain-ai/langchain
sprite $langchain [100x100/16z] {
xTY7ShEy5aPXoHXsUPVdtF_TdW33e8d5kFwTv-ibMH6RNbvrEfrEfzFfTAgrlAlEUh_TV1HPFhvLbn-_rF8HNlHnuFibFl7ST96KucMAZ0auclzIc7_y3yyK
Rv8KG5rq4dC4y1IVK4v0lT-RwmgKubFRKdeD8CKNI06zeLH0V8aIEWSiNwM0sclSQAHI4k-IG_a5HCipmJw8HC3lHD3AP65wSiW6dab3Tur9DEGEjO95yf12
mIp4yTR2afO3os4FoIDfi8fhiajh6nKNZLmICt0zbOYCzLVOo99QDcJG2XkWBXukH9cG8P1Fa6hgrxRXefKoeAvBH8zMCOQOoI2IdHb7EnM4bCdM48SKQaQj
YSdO1MmNUn3t1AMMMY34aQ2T60QYuNiZw52odf-F8tB3BPA6s2aeAqXwOXz9gfy8wk3ZP6AHlMsn0D6ZfN4yT-6KQjDu8RGsTP-fQuDZTPv8gRtDbO8oDwuN
CW4YmVlt41p9kN6qwoKmNSSoceqNfaG1FYMjsyD69Djb6KXQcJ1EDWt365uOfl34hq6tKJcYTLij89ETD2So9Yw3XPLvERsXFsuar0tjI3G19XG33EP3gHKG
BpTGqsX7WWiIG3Pm6UDIr4lSWEqgA_eozaWfA9i5IioKDevU2tvrEhR6iG3A5a71Ii4kmYV0atkvDIg8nrkhL2nPfDF8wUZUJqvPLKWUHTOBSh2GWs0bu-YC
9ZYwVhIKJOCG2mVNrhF3qx_lv_P29aU2kL3TpIe4YmHV8sb093sQjiOFmiM11BTB7Mq2jeaas1Yf31iXawwyKJQrOic1ZF6dCKIcEyZ5B012uS0rZpTpsK5o
mCqYp5mex0e1q0uvaxxqzRIz0N4d9UJcPkOc8CtTs-iHexaUd8aUD7uevqKWtqOcDcbArrDx_N44z2F3pUOQ7JUEIDJPaoEHn1lArjY1-1e1TwzKviZtP4Bj
Fg03uWiazLu4rEyzsIe3bajqBr4AOAxF2WcirupIZrIOndxbDkE14C2oXDfhb1L0fgI8RCMFx0gnvCKQgEKX5ebxD7mMVSckF0_M6fiw--xBkFgoyZVst9TQ
v-__QgVJwNGwdVuF
}

' https://github.com/ClickHouse/ClickHouse
sprite $clickhouse [100x100/16z] xTQb0S1044N1CFRVR-ntORNptE7ORSgbFdg_MzrWC1WC1eF1O30O34OVrJ0O30Q3mJ0pC1WC1eF1O2pHNyOUCQuQ30P3EW

' https://github.com/NVIDIA
sprite $nvidia [100x100/16z] {
xPY7SlGu38D5W4JgpF_-Jtj5sWZoLcSlqox6LfVX9rA4M_mQ7JfqwD2XGuTQj8XcHSoV_kclzQjlpDWlwYbbV4EfbsVq-nW7esAN4140IqC_dqSBW5bLrL5C
PfNqSmn4C7D4r98KixINqHu0a1woOkeb8lPYyZw2MTxNZ9mfxg7KJGZ-h16aganf_18HRn6X04lFvs62L4cilQjAHXU1V0IfjnjLGch6GqGxzuUA4HnTLtec
3r0oeSiCKxptTnbSofG8TvD3UMjd1qlVOu0BuRC7QG4oCqdcsip5hnvBxMVGvIr--JpO0siEmhFFQ8yEPjKkB55VOqIq0SqJLM6egpaW3QaTUJXdrxeceJC-
OaYJCYU5e7OnLaGxfIMx40Z8--w4R1ce5R5b4g1K1749oL72r2C6MBDVEWAOzM3FIMEQfcCc9Bg8gv226TvZ83pzN4CMx2DjeYYeXtbCnbYksSEv3hlGGxxE
YA9D-d0-SdPzcY5UbWPUxCj6F69ufysuSs6Okct1BUBEUH0zaLcEXBnWHb-pch1lRaOyw5rkqqzvOMKernPy6KRQUon1Qaa4B2-iZ1TfHMopa1uTI-fw8Yzp
oNAXiEB9qbt6TbwRM-igGpnvTKNqQkWEWwZf4RfNn6kCOi2dD9yR4OQQOG7Bj1jI36qOywYImJe_CPfhnggjUpcDHsmOgiGdF6JFJbS69kMIyJ935TT59QYL
CFg0TNxYDILlvW7KUlHzmHT4MUhgXDPDiKaYAbQnfcClz8UrbjUr5PZCJ4GWecrcLXdMTcF6DS4GBjRKsUMybjenshArhNDULn71slRE2AZ8VyM8quoQWDZo
Iu-lTrds0ETj20a0P9PMGgAPqJnBzndhSPM8jtvA2kga5qjAB6Lw3nFkCdozPEzU-DmzRBcNTp0yqOwaSuQgkEG0trdjPkJ6Nqci7bHV4zCHhwCDJ5XK5NU4
h7NKMUKxgHvu20XabPwxh_LXUle3OxeITflxx3d6McDT7OItFy7mEAliS-S2ifp0CmoB232pL1XYNxHH_Zl38sSDEVWFCIp-lkTN1uEzf_fxV9MgIrvTNgtJ
GiQtD9-0d_x6wIlwP_vfqQneYF-73XqwTEZGeKD_0m
}

' https://github.com/VictoriaMetrics/VictoriaMetrics
sprite $victoriametrics [100x100/16z] {
xTV7SGD140F0oM3pprP_6MYg2qUFtpcqB0bEpbbbB0S2zHRefm0W0G420aG9Hyv5CUDZp5K484000WGWG00212100084840qaSaf4QQuq4T2RGi9hHqabtQG
tDb1ScK1MJKwiYrqPDld2DIDAVD_c-qLw084gW219a2mA2FQuqYk0GG8-1BWwmJ4YPbS8GGWS1KG9lQtfWkPo7V_Vddn423mY3_X3_WphIrQ8VGliRf5WVXH
IaXzYsw8N0a8Rj7S0Uy5i1F3DTs9vvUayxbDra8WFblqiqNXehNCGIJV9hi79XOWG2ZYAwwvHN40m6yR42RWps-USOiUk1yGk1iGkzSH9sfRr1Mu2H0b776Y
ze7SaHCl6HB2X2FZ0O8G9rnnmP5fn0X7d71aUW424ISScNfOS6Gk2WfV
}

' https://dnsmasq.org/doc.html
sprite $dnsmasq [65x65/16z] {
xTN9Wh8m40HW3zLxQzx_QLtQcIGe_lmCLxzZcYfsEFtJrzTNMt4WF1nBb_zDAzCJYxONMt4cl26vR5RKvFmCiwZTkTkT2bS7PnlMurnXhT147qq2WFHZms-S
pKtMg8NBfugA6m1nKocwnaC1yj4mvmbWDztWgO2CXZbFPhhD8XZKxqWl03WglyaoPMheUGcTc4Ta5-5klpmpRT5GnozXMkmkSatr-7Dcu5vGjuzZiOTj0fqA
WDWJBuJnQ1FKftpKSMxnSJEd0uWC8JomvynLc4Kz1w9Hm6xcTv41S3tt1Ck10Re3E3j5jYU1UebvbIWxWTO9dnKo3WhMdXZcfLP9FJEKeFFE9DgTyxGQq5xW
umOxev3bHF13SkW50ikPcrNRWgc8MWxJ4KJrxcRmzWEKVo2O7YJF_S2z8C2vco9Qnx3SAS1jk10Ytxam4ukjpGZdDd5Gv98n068c0AJvWk5jmK2UGoX0ugs4
422BCSDwzDIA0pOE7M1la-3v_NI2jxcW987ZqMu4IBONPm58gqD0qORnInM0c03IIrjZ1808a3uV1IM5Y3NRHsTb8ictNtqxulHmA5yE5PG3yOs6ZU56m-Pu
QUVyj68UxviFOxXZW-E-lcu
}



@enduml
